// Public-domain ref10 subset from SUPERCOP.

#include "internal.h"

#include "fe_0.c"
#include "fe_1.c"
#include "fe_add.c"
#include "fe_cmov.c"
#include "fe_copy.c"
#include "fe_invert.c"
#include "fe_mul.c"
#include "fe_neg.c"
#include "fe_sq.c"
#include "fe_sq2.c"
#include "fe_sub.c"
#include "fe_tobytes.c"
#include "ge_madd.c"
#include "ge_p1p1_to_p2.c"
#include "ge_p1p1_to_p3.c"
#include "ge_p2_dbl.c"
#include "ge_p3_0.c"
#include "ge_p3_dbl.c"
#include "ge_p3_to_p2.c"
#include "ge_precomp_0.c"
#include "ge_scalarmult_base.c"
